name: Test1
run-name: ${{ github.actor }} is testing
on: 
  push:
    branches:
      - 'hotfix/**'
      - 'release/**'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started"
